openapi: "3.0.2"
info:
  title: GY Accounts API
  description: API for managing accounts for GYCODING services.
  version: "1.0.0"
servers:
  - url: https://gy-accounts.onrender.com/
    description: Production server
  - url: http://localhost:8002/
    description: Local server
paths:
  /login:
    post:
      description: Log in to an existing account.
      operationId: login
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username or email of the account trying to be logged in.
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: Password of the account trying to be logged in.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts
  /signup:
    post:
      description: Register a new account.
      operationId: signUp
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username of the account trying to be logged in.
        - in: query
          name: email
          required: true
          schema:
            type: string
          description: Email of the account trying to be logged in.
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: Password of the account trying to be logged in.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts
  /session:
    post:
      description: Get a representation of a session.
      operationId: getSession
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username or email of the account trying to get the session from.
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: Password of the account trying to get the session from.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts
  /update/username:
    put:
      description: Modifies the username of an existing account.
      operationId: updateUsername
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username or email of the account to update.
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: Password of the account to update.
        - in: query
          name: new-user
          required: true
          schema:
            type: string
          description: New username.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts
  /update/email:
    put:
      description: Modifies the email of an existing account.
      operationId: updateEmail
      parameters:
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username or email of the account to update.
        - in: query
          name: password
          required: true
          schema:
            type: string
          description: Password of the account to update.
        - in: query
          name: new-email
          required: true
          schema:
            type: string
          description: New email.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts
  /update/password/{forgotten}:
    put:
      description: Modifies the password of an existing account.
      operationId: updatePassword
      parameters:
        - in: path
          name: forgotten
          required: true
          schema:
            type: boolean
          description: Whether the operation is because of a forgotten password or not.
        - in: query
          name: user
          required: true
          schema:
            type: string
          description: Username or email of the account to update.
        - in: query
          name: password
          required: false
          schema:
            type: string
          description: Password of the account to update.
        - in: query
          name: new-password
          required: true
          schema:
            type: string
          description: New password.
      responses:
        "200":
          description: OK
      tags:
        - GY Accounts