name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
     uses: GY-CODING/.github/.github/workflows/koyeb-deploy.yml@master
     secrets: inherit
     with: 
       url: ${{ secrets.ACCOUNTS_KOYEB_DEPLOY_URL }}
